# Use the Python slim image as the base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Install required system dependencies, including libpcap
RUN apt-get update && apt-get install -y \
    libpcap-dev \
    iproute2 \
    iptables \
    net-tools \
    python3-dev \
    telnetd \
    openssh-server \
    gcc && \
    rm -rf /var/lib/apt/lists/*

RUN systemctl enable ssh --now && \
    systemctl start ssh

# Copy requirements.txt and install dependencies
COPY ../requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy the entrypoint script into the container
COPY testbed/entrypoint.sh /app/entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint.sh

# Expose necessary ports for the firewall
EXPOSE 80 443

# Use the entrypoint script to start the firewall program
ENTRYPOINT ["/app/entrypoint.sh"]
COPY testbed/entrypoint.sh /app/entrypoint.sh
