version: "3.8"

services:
  firewall:
    build:
      context: .
      dockerfile: Dockerfile.firewall
    container_name: firewall-machine
    networks:
      - firewall-net
    ports:
      - "22:22"
      - "23:23"
      - "80:80"
      - "443:443"
    cap_add:
      - NET_ADMIN

  scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    container_name: scanner-machine
    networks:
      - firewall-net
    stdin_open: true
    tty: true

networks:
  test-network:
    driver: bridge
